camera:
  ros__parameters:
    image_degradation: 0.0
    image_mean_threshold: 25.0 # threshold for the necessary image shift to be considered degraded
    do_drop_rgb_camera: False

depth:
  ros__parameters:
    depth_degradation: 0.0
    do_drop_depth_camera: False

sensor_fusion:
  ros__parameters:
    topic_camera_input: "rgb_camera"
    modality: 0  # 0=fusion
    delta_t_threshold: 0.01  # max time difference between synchronous frames
    
image_enhancement:
  ros__parameters:
    
segmentation:
  ros__parameters:
    
blackboard_setter:
  ros__parameters:
    